apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-one
spec:
  template:
    metadata:
      labels:
        app: wordpress-one
    spec:
      containers:
      - name: wordpress
        image: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1
        - name: WORDPRESS_DB_PASSWORD
          value: "example"
        ports:
        - containerPort: 80
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "example"
