apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-nginx
spec:
  template:
    metadata:
      labels:
        app: example-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
