apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-two-hpa
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: wordpress-two
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
