apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-two
spec:
  # replicas: 1
  template:
    metadata:
      labels:
        app: wordpress-two
    spec:
      containers:
      - name: wordpress
        image: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: "wordpress-two-mysql-service"
        - name: WORDPRESS_DB_PASSWORD
          value: "example"
        # resources:
        #   requests:
        #     cpu: 1500m
        #     memory: 2560Mi
        ports:
        - containerPort: 80
