apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.client }}-wp
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ .Values.client }}-wp
  minReplicas: {{ .Values.wordpress.hpa.min }}
  maxReplicas: {{ .Values.wordpress.hpa.max }}
  targetCPUUtilizationPercentage: {{ .Values.wordpress.hpa.target }}
