client: borubar
mysql:
  image: "mysql:5.5"
  pass: dupa
  port: 3306
wordpress:
  replicas: 1
  requests:
    cpu: 100m
    memory: 128Mi
  image: "wordpress:4.4"
  hpa:
    min: 1
    max: 1
    target: 90
