client: stefan
mysql:
  image: "mysql:5.6"
  pass: foo
  port: 3306
wordpress:
  replicas: 1
  requests:
    cpu: 100m
    memory: 128Mi
  image: "wordpress:4.8"
  hpa:
    min: 1
    max: 2
    target: 15
